<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class OutputRecordsTableSeeder extends Seeder
{
    private $table = 'output_records';
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'gl_id' => '1',
                'line_id' => '1',
                'time_hours_of' => '1',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '80',
                'defect_qty' => '1',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'gl_id' => '1',
                'line_id' => '1',
                'time_hours_of' => '2',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '90',
                'defect_qty' => '2',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'gl_id' => '1',
                'line_id' => '1',
                'time_hours_of' => '3',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '100',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'gl_id' => '1',
                'line_id' => '1',
                'time_hours_of' => '4',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '110',
                'defect_qty' => '1',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'gl_id' => '3',
                'line_id' => '1',
                'time_hours_of' => '5',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '120',
                'defect_qty' => '1',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'gl_id' => '3',
                'line_id' => '1',
                'time_hours_of' => '6',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '90',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'gl_id' => '3',
                'line_id' => '1',
                'time_hours_of' => '7',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '105',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'gl_id' => '3',
                'line_id' => '1',
                'time_hours_of' => '8',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '120',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'gl_id' => '1',
                'line_id' => '2',
                'time_hours_of' => '1',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '70',
                'defect_qty' => '1',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'gl_id' => '1',
                'line_id' => '2',
                'time_hours_of' => '2',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '90',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'gl_id' => '1',
                'line_id' => '2',
                'time_hours_of' => '3',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '120',
                'defect_qty' => '2',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'gl_id' => '1',
                'line_id' => '2',
                'time_hours_of' => '4',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '80',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'gl_id' => '1',
                'line_id' => '2',
                'time_hours_of' => '5',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '90',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'gl_id' => '1',
                'line_id' => '2',
                'time_hours_of' => '6',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '100',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'gl_id' => '1',
                'line_id' => '2',
                'time_hours_of' => '7',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '110',
                'defect_qty' => '1',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'gl_id' => '1',
                'line_id' => '2',
                'time_hours_of' => '8',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '100',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'gl_id' => '2',
                'line_id' => '3',
                'time_hours_of' => '1',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '130',
                'defect_qty' => '2',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'gl_id' => '2',
                'line_id' => '3',
                'time_hours_of' => '2',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '90',
                'defect_qty' => '1',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'gl_id' => '2',
                'line_id' => '3',
                'time_hours_of' => '3',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '100',
                'defect_qty' => '1',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'gl_id' => '2',
                'line_id' => '3',
                'time_hours_of' => '4',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '80',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'gl_id' => '2',
                'line_id' => '3',
                'time_hours_of' => '5',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '110',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'gl_id' => '2',
                'line_id' => '3',
                'time_hours_of' => '6',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '70',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'gl_id' => '2',
                'line_id' => '3',
                'time_hours_of' => '7',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '110',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 24,
                'gl_id' => '2',
                'line_id' => '3',
                'time_hours_of' => '8',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '120',
                'defect_qty' => '1',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'gl_id' => '1',
                'line_id' => '4',
                'time_hours_of' => '1',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '110',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 26,
                'gl_id' => '1',
                'line_id' => '4',
                'time_hours_of' => '2',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '100',
                'defect_qty' => '2',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 27,
                'gl_id' => '1',
                'line_id' => '4',
                'time_hours_of' => '3',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '90',
                'defect_qty' => '2',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 28,
                'gl_id' => '1',
                'line_id' => '4',
                'time_hours_of' => '4',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '80',
                'defect_qty' => '1',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 29,
                'gl_id' => '1',
                'line_id' => '4',
                'time_hours_of' => '5',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '110',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 30,
                'gl_id' => '1',
                'line_id' => '4',
                'time_hours_of' => '6',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '130',
                'defect_qty' => '0',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 31,
                'gl_id' => '1',
                'line_id' => '4',
                'time_hours_of' => '7',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '110',
                'defect_qty' => '1',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 32,
                'gl_id' => '1',
                'line_id' => '4',
                'time_hours_of' => '8',
                'time_date' => date('Y-m-d'),
                'target' => '100',
                'output' => '90',
                'defect_qty' => '1',
                'endline_ftt' => '',
                'downtime_min' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];
        $this->db->table($this->table)->insertBatch($data);
    }
}
